version: "3.9"
services:
  mongo:
    image: "mongo:3.6.21-xenial"
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo:/data/db
    command: --smallfiles
  postgres:
    image: postgres
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: money-manager