version: "3.9"
services:

  postgres:
    image: postgres
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: money-manager